# Generated by Django 5.0.1 on 2024-01-14 03:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FusionPod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('production_date', models.DateField(auto_now_add=True)),
                ('purchased_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
