# Generated by Django 4.2.7 on 2024-01-17 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product_tracking', '0002_fusionpod_device_name_alter_fusionpod_purchased_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastSnapShot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('temperature_celsius', models.FloatField()),
                ('humidity', models.FloatField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_tracking.fusionpod')),
            ],
        ),
    ]
